site_name: r2c-checks
theme:
  name: "material"
  favicon: "images/favicon.ico"
  logo: "images/r2c-logo-silhouette.png"
  palette:
    primary: "black"
    secondary: "indigo"
markdown_extensions:
  - codehilite
