site_name: bento-checks
theme:
  name: "material"
  favicon: "images/favicon.ico"
  logo: "images/r2c-logo-silhouette.png"
  palette:
    primary: "black"
    secondary: "indigo"
markdown_extensions:
  - codehilite
google_analytics: ["UA-106134149-11", "checks.bento.dev"]
