site_name: bento-checks
theme:
  name: "material"
  favicon: "images/favicon.ico"
  logo: "images/bento-logo-24px-dark.png"
  palette:
    primary: "black"
    secondary: "indigo"
markdown_extensions:
  - codehilite
